Offered services
front-end-by-rimantas/18-grupe-portfolio-personal pull request #44
Opened 2020-10-16 11:40 UTC by Andzej-F

*Icons don't have to be the same as in the original website, so I used font awesome icons/ this decision was approved by Rimantas during the lecture 
* minor issue with the description- in the original site there are two lines, right now I cannot make the text appear in two lines, this task will be included in my new issue (transforming header & text to js), 
*right now I just want to check if it is possible to merge just to add something to  the full picture, because I am stuck with my task for too long

If you'll notice anything else-please inform me :)

2020-10-16 14:14 UTC, Slashass approved these changes

2020-10-16 17:20 UTC, Slashass approved these changes, later dismissed

2020-10-18 08:04 UTC, belauzas requested changes

2020-10-18 08:04 UTC, belauzas commented on css/layout.css
> +@media (max-width: 1300px ) {
Pašalinti esantį tarpą `1300px )` - viena vertus tai sumažins pakeisti kodo kiekį, antra vertus bus vientisumas tarp atidarančio ir uždarančio skliaustelių.

2020-10-18 08:04 UTC, belauzas commented on css/layout.css
> +@media (max-width: 1100px ) {
Pašalinti esantį tarpą `1100px )` - viena vertus tai sumažins pakeisti kodo kiekį, antra vertus bus vientisumas tarp atidarančio ir uždarančio skliaustelių.

2020-10-18 08:04 UTC, belauzas commented on css/layout.css
> +@media (max-width: 900px ) {
Pašalinti esantį tarpą `900px )` - viena vertus tai sumažins pakeisti kodo kiekį, antra vertus bus vientisumas tarp atidarančio ir uždarančio skliaustelių.

2020-10-18 08:04 UTC, belauzas commented on css/layout.css
> +@media (max-width: 700px ) {
Pašalinti esantį tarpą `700px )` - viena vertus tai sumažins pakeisti kodo kiekį, antra vertus bus vientisumas tarp atidarančio ir uždarančio skliaustelių.

2020-10-18 08:04 UTC, belauzas commented on index.html
>                          showing Scrooge some different futures.</p>
Normaliu atveju, tai turėtų būti vientisas tekstas, t.y. be enter'ių.

2020-10-18 08:04 UTC, belauzas commented on index.html
> +                        kept, or made and neglected.</p>
Normaliu atveju, tai turėtų būti vientisas tekstas, t.y. be enter'ių.

2020-10-18 08:04 UTC, belauzas commented on js/components/services/renderServices.js
> +
Jei `params` objekto validacija yra kitos užduoties dalis - viskas OK, bet jei taip suplanuota nėra - tokia validacija turėtų būti atlikta su šia užduotimi.

2020-10-18 08:04 UTC, belauzas commented on js/components/services/generateService.js
> +
Jei `service` objekto validacija yra kitos užduoties dalis - viskas OK, bet jei taip suplanuota nėra - tokia validacija turėtų būti atlikta su šia užduotimi.

2020-10-18 19:15 UTC, belauzas commented on css/custom.css
> +                color: #282828;;
dvygubas kabletaškis

2020-10-18 19:26 UTC, belauzas approved these changes

2020-10-19 11:58 UTC, IevaRugine approved these changes

2020-10-19 18:42 UTC, Slashass approved these changes

2020-10-19 18:49 UTC, merged